services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./thumbnails:/app/thumbnails
      - ./audio:/app/audio
    depends_on:
      - asr

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  asr:
    build: ./asr
    ports:
      - "8000:8000"
